### ISSUE TITLE
IOError: [Errno 13] Permission denied: 'victim_info_2012_2018.csv'

### ISSUE THREAD

**Issue by chankeypathak** [craftbase/chicago-murders#1]
`parsehtml.py` is breaking intermittently with below error:

There's no fixed pattern. Sometimes it scraps 5-6 months successfully but most of the times it breaks after fetching data for `February 2012`.
```

Traceback (most recent call last):
  File "chicago-murders/src/data/extractor/parsehtml.py", line 93, in <module>
    get_dynamic_content(link)
  File "chicago-murders/src/data/extractor/parsehtml.py", line 28, in get_dynamic_content
    parsedata(soup)
  File chicago-murders/src/data/extractor/parsehtml.py", line 85, in parsedata
    victim_info_df.to_csv('victim_info_2012_2018.csv', mode='a', header=False)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1383, in to_csv
    formatter.save()
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\formats\format.py", line 1460, in save
    compression=self.compression)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\io\common.py", line 334, in _get_handle
    f = open(path, mode)
IOError: [Errno 13] Permission denied: 'victim_info_2012_2018.csv'
```

**Comment by chankeypathak** [comment]
Not facing the issue after some recent commits, don't know what exactly fixed it. Closing the issue for now, will reopen if it reoccurs.
